# src/memory/memory_service.py
from typing import Optional, Dict, Any, List
from datetime import datetime, timedelta
import json
import hashlib

from src.memory.vector_store import VectorStore
from src.memory.graph_store import GraphStore
from src.memory.time_series_store import TimeSeriesStore
from src.models.dag import DAG
from src.utils.logging import logger
from src.core.config import get_settings

settings = get_settings()


class MemoryService:
    """
    Enterprise Memory System
    
    Combines:
    - Vector DB for semantic search
    - Graph DB for relationship storage
    - Time Series DB for metrics
    """
    
    def __init__(
        self,
        vector_store: Optional[VectorStore] = None,
        graph_store: Optional[GraphStore] = None,
        time_series_store: Optional[TimeSeriesStore] = None
    ):
        self.vector_store = vector_store or VectorStore()
        self.graph_store = graph_store or GraphStore()
        self.time_series_store = time_series_store or TimeSeriesStore()
        
        logger.info("✅ Memory Service initialized")
    
    async def find_similar_tasks(
        self,
        goal: str,
        target: Optional[str] = None,
        limit: int = 10
    ) -> List[Dict[str, Any]]:
        """Find similar tasks using vector search"""
        
        try:
            # Generate embedding for query
            query_text = f"{goal} {target or ''}"
            
            # Search vector store
            results = await self.vector_store.search(
                query=query_text,
                limit=limit,
                filter={"type": "task"}
            )
            
            return results
            
        except Exception as e:
            logger.error(f"Failed to find similar tasks: {e}")
            return []
    
    async def find_similar_plan(
        self,
        goal: str,
        target: Optional[str] = None,
        tenant_id: Optional[str] = None,
        min_success_rate: float = 0.7
    ) -> Optional[Dict[str, Any]]:
        """Find similar successful plan"""
        
        try:
            # Search vector store for plans
            query_text = f"{goal} {target or ''}"
            
            results = await self.vector_store.search(
                query=query_text,
                limit=5,
                filter={
                    "type": "plan",
                    "tenant_id": tenant_id
                }
            )
            
            # Find best match with high success rate
            for result in results:
                if result.get("success_rate", 0) >= min_success_rate:
                    return result
            
            return None
            
        except Exception as e:
            logger.error(f"Failed to find similar plan: {e}")
            return None
    
    async def store_plan(
        self,
        goal: str,
        target: Optional[str],
        dag: DAG,
        user_id: str,
        tenant_id: str
    ) -> str:
        """Store plan in memory"""
        
        plan_id = f"plan_{hashlib.md5(goal.encode()).hexdigest()[:8]}"
        
        try:
            # Store in vector DB
            plan_data = {
                "id": plan_id,
                "goal": goal,
                "target": target,
                "dag": dag.model_dump(),
                "task_count": dag.total_tasks,
                "estimated_duration": dag.estimated_duration_seconds,
                "estimated_cost": dag.estimated_total_cost,
                "user_id": user_id,
                "tenant_id": tenant_id,
                "created_at": datetime.utcnow().isoformat(),
                "type": "plan"
            }
            
            await self.vector_store.upsert(
                id=plan_id,
                vector=None,  # Will be generated by store
                metadata=plan_data,
                text=f"{goal} {target or ''}"
            )
            
            # Store in graph DB
            await self.graph_store.create_plan_node(plan_id, plan_data)
            
            # Create relationships between tasks
            for task_id, task in dag.nodes.items():
                await self.graph_store.create_task_node(task_id, task.model_dump())
                await self.graph_store.create_relationship(
                    plan_id, "CONTAINS", task_id
                )
            
            for edge in dag.edges:
                await self.graph_store.create_relationship(
                    edge["from"], "DEPENDS_ON", edge["to"]
                )
            
            logger.info(f"✅ Stored plan {plan_id} with {dag.total_tasks} tasks")
            return plan_id
            
        except Exception as e:
            logger.error(f"Failed to store plan: {e}")
            return plan_id
    
    async def store_task_result(
        self,
        task_id: str,
        process_id: str,
        result: Dict[str, Any]
    ):
        """Store task execution result"""
        
        try:
            # Store in time series DB
            await self.time_series_store.write_points([
                {
                    "measurement": "task_execution",
                    "tags": {
                        "task_id": task_id,
                        "process_id": process_id,
                        "status": result.get("status", "unknown")
                    },
                    "fields": {
                        "duration": result.get("duration_seconds", 0),
                        "cost": result.get("cost", 0),
                        "success": 1 if result.get("status") == "success" else 0
                    },
                    "time": datetime.utcnow()
                }
            ])
            
            # Update graph with result
            await self.graph_store.update_task_result(task_id, result)
            
        except Exception as e:
            logger.error(f"Failed to store task result: {e}")
    
    async def store_execution_result(
        self,
        process_id: str,
        result: Dict[str, Any]
    ):
        """Store execution result"""
        
        try:
            # Store in time series DB
            await self.time_series_store.write_points([
                {
                    "measurement": "execution",
                    "tags": {
                        "process_id": process_id,
                        "status": result.get("status", "unknown"),
                        "tenant_id": result.get("tenant_id", "unknown")
                    },
                    "fields": {
                        "total_tasks": result.get("total_tasks", 0),
                        "completed_tasks": result.get("completed_tasks", 0),
                        "failed_tasks": result.get("failed_tasks", 0),
                        "total_cost": result.get("total_cost", 0),
                        "duration": result.get("duration_seconds", 0)
                    },
                    "time": datetime.utcnow()
                }
            ])
            
        except Exception as e:
            logger.error(f"Failed to store execution result: {e}")
    
    async def get_execution_metrics(
        self,
        tenant_id: str,
        start_time: datetime,
        end_time: datetime
    ) -> Dict[str, Any]:
        """Get execution metrics for time period"""
        
        try:
            # Query time series DB
            results = await self.time_series_store.query(
                f"""
                SELECT count(*) FROM execution
                WHERE tenant_id = '{tenant_id}'
                AND time >= '{start_time.isoformat()}Z'
                AND time <= '{end_time.isoformat()}Z'
                """
            )
            
            return results
            
        except Exception as e:
            logger.error(f"Failed to get execution metrics: {e}")
            return {}


# src/memory/vector_store.py
class VectorStore:
    """Vector database for semantic search"""
    
    def __init__(self):
        # In-memory implementation for development
        self.vectors = {}
        self.metadata = {}
        logger.info("✅ Vector Store initialized (in-memory)")
    
    async def upsert(
        self,
        id: str,
        vector: Optional[List[float]],
        metadata: Dict[str, Any],
        text: str
    ):
        """Upsert vector with metadata"""
        
        # Store metadata
        self.metadata[id] = {
            "metadata": metadata,
            "text": text,
            "timestamp": datetime.utcnow().isoformat()
        }
        
        # In production, generate embedding and store in vector DB
    
    async def search(
        self,
        query: str,
        limit: int = 10,
        filter: Optional[Dict] = None
    ) -> List[Dict[str, Any]]:
        """Search for similar items"""
        
        results = []
        
        # Simple text matching for development
        for id, data in self.metadata.items():
            # Apply filter
            if filter:
                match = True
                for key, value in filter.items():
                    if data["metadata"].get(key) != value:
                        match = False
                        break
                if not match:
                    continue
            
            # Simple text match scoring
            if query.lower() in data["text"].lower():
                results.append({
                    "id": id,
                    "score": 0.8,
                    **data["metadata"]
                })
        
        return results[:limit]


# src/memory/graph_store.py
class GraphStore:
    """Graph database for relationships"""
    
    def __init__(self):
        self.nodes = {}
        self.edges = []
        logger.info("✅ Graph Store initialized (in-memory)")
    
    async def create_plan_node(self, plan_id: str, data: Dict):
        """Create plan node"""
        self.nodes[plan_id] = {
            "type": "plan",
            "data": data,
            "created_at": datetime.utcnow().isoformat()
        }
    
    async def create_task_node(self, task_id: str, data: Dict):
        """Create task node"""
        self.nodes[task_id] = {
            "type": "task",
            "data": data,
            "created_at": datetime.utcnow().isoformat()
        }
    
    async def create_relationship(self, from_id: str, relation: str, to_id: str):
        """Create relationship between nodes"""
        self.edges.append({
            "from": from_id,
            "relation": relation,
            "to": to_id,
            "created_at": datetime.utcnow().isoformat()
        })
    
    async def update_task_result(self, task_id: str, result: Dict):
        """Update task with result"""
        if task_id in self.nodes:
            self.nodes[task_id]["result"] = result
            self.nodes[task_id]["completed_at"] = datetime.utcnow().isoformat()


# src/memory/time_series_store.py
class TimeSeriesStore:
    """Time series database for metrics"""
    
    def __init__(self):
        self.points = []
        logger.info("✅ Time Series Store initialized (in-memory)")
    
    async def write_points(self, points: List[Dict]):
        """Write time series points"""
        for point in points:
            self.points.append({
                **point,
                "stored_at": datetime.utcnow().isoformat()
            })
    
    async def query(self, query: str) -> Dict[str, Any]:
        """Query time series data"""
        
        # Simple in-memory query simulation
        results = {
            "execution_count": len([p for p in self.points if p.get("measurement") == "execution"]),
            "task_count": len([p for p in self.points if p.get("measurement") == "task_execution"])
        }
        
        return results